### ISSUE TITLE
[RFC-意见征求] 关于项目推广

### ISSUE THREAD

**Issue by Itsusinn** [MeowCat-Studio/mesagisto#39]
为了提高项目的知名度
可能会增加`向群聊内定时发送本项目的repo地址`的广播功能，默认开启，可手动关闭

> 这是一个 RFC-Request for Comments 即意见征求issue
> 你可以在本issue内自由地发表自己的相关意见

**Comment by XieXiLin158** [comment]
?

**Comment by DreamOneX** [comment]
智齿，~~不过建议默认关闭以免挨骂~~
