### ISSUE TITLE
提案: proxy代理模式

### ISSUE THREAD

**Issue by Itsusinn** [MeowCat-Studio/mesagisto#43]
实际上我们更想要的是这样一种功能，比如通过转发消息达到:  不打开QQ就能从telegram一侧处理所有的qq消息的效果

**Comment by Itsusinn** [comment]
但是，存在着不可藐视的问题。假设通过telegram接收所有qq消息，那么将不可避免地创建与qq联系人数量相等的tg频道，这对于tg来说是一个不小的负担。

**Comment by Dreamail** [comment]
@Itsusinn 用消息前缀吧

**Comment by XieXiLin158** [comment]
你说出了我刚刚在想的功能）



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月12日(星期三) 下午5:35
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: Re: [MeowCat-Studio/mesagisto] 提案: proxy代理模式 (Issue #43)





 
@Itsusinn 用消息前缀吧
 
&mdash;
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Itsusinn** [comment]
那么这样如何:  默认情况下所有聊天通过机器人私人聊天转发，用前缀加以标识。
如果想要回复一条消息，那么就通过引用回复(或者指令)来切换消息的接收者，达到回复的目的。


还可以为特别的某个联系人创建单独的频道，避免过于频繁的接收者切换。

**Comment by Dreamail** [comment]
之前本来就想魔改信使实现的了
我是很希望这个功能出的

**Comment by Itsusinn** [comment]
https://www.matrix.org/
社区万岁！

开摆

**Comment by Dreamail** [comment]
@Itsusinn ?都可以摆

**Comment by MlgmXyysd** [comment]
@Itsusinn 摆起来摆起来

**Comment by XieXiLin158** [comment]
@Itsusinn 大力摆.jpg
