### ISSUE TITLE
[FR] bungeecord 与velocity 支持

### ISSUE THREAD

**Issue by Haocen2004** [MeowCat-Studio/mesagisto#47]
目前绝大多数的mc服务端都可以放在bungee后面部署
~~可以说是开发一次全版本全种类通用了（~~

**Comment by Itsusinn** [comment]
~~我不会~~
~~(其实是有学习成本)~~

**Comment by Itsusinn** [comment]
bungee现已支持 https://github.com/MeowCat-Studio/bungeecord-message-source

但...Bungee/Waterfall 对高版本Forge以及Fabric的兼容性如何？

**Comment by Itsusinn** [comment]
重复 #56
