### ISSUE TITLE
请问连接群聊的目标能否加上私聊？

### ISSUE THREAD

**Issue by SyuueenN** [MeowCat-Studio/mesagisto#53]
能否将其他平台群聊连接到一个私聊，来达到比如通过企鹅免梯访问外网群的功能？

**Comment by Itsusinn** [comment]
按照目前架构恐怕非常困难。

PS: 如果你想要实现此功能的话，已经有一个叫Matrix的项目实现了。几乎可以无痕迹地通过一个APP收发其他所有平台的消息。（qq的支持比较欠缺）

https://matrix.org/

**Comment by SyuueenN** [comment]
> 按照目前架构恐怕非常困难。
> 
> PS: 如果你想要实现此功能的话，已经有一个叫Matrix的项目实现了。几乎可以无痕迹地通过一个APP收发其他所有平台的消息。（qq的支持比较欠缺）
> 
> https://matrix.org/
> 
> Duplicated: #43

可以可以，这就去看看

**Comment by XieXiLin3** [comment]
……Not planned……
