### ISSUE TITLE
[建议]要是mc客户端支持bungeecord就更好了

### ISSUE THREAD

**Issue by ABCDCreeper** [MeowCat-Studio/mesagisto#61]
要是mc客户端支持bungeecord就更好了，我这种开waterfall群组服务器的，每个服务器上都要装，很烦

**Comment by XieXiLin3** [comment]
目前正在支持， #47
[仓库地址](https://github.com/MeowCat-Studio/bungeecord-message-source)

**Comment by XieXiLin3** [comment]
（催更即胜利）

**Comment by Itsusinn** [comment]
文档已更新 https://docs.mesagisto.org/zh-CN/minecraft-message-source/bungee/
